"use strict";
const moneyFmt=new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const $=id=>document.getElementById(id);
const ingredients={
 "Synthetischer Gin":{color:"#6ce9dd",unlock:1},"Wodka":{color:"#b9d9ff",unlock:1},"Dark Rum":{color:"#a2624b",unlock:1},"Bourbon":{color:"#d89445",unlock:2},
 "Blue Curaçao":{color:"#2c8cff",unlock:1},"Kirschlikör":{color:"#d73368",unlock:1},"Kaffee-Likör":{color:"#5f3e35",unlock:1},"Orangenlikör":{color:"#ef9b44",unlock:2},
 "Limettensaft":{color:"#a6dc55",unlock:1},"Zitronensaft":{color:"#f4dc53",unlock:1},"Ananassaft":{color:"#f3c952",unlock:2},"Cranberry":{color:"#b72550",unlock:1},
 "Tonic":{color:"#bdeeff",unlock:1},"Ginger Synth":{color:"#d5ae62",unlock:1},"Soda":{color:"#d7f7ff",unlock:1},"Neon-Sirup":{color:"#ff4fc7",unlock:1},
 "Rauchessenz":{color:"#77768e",unlock:3},"Plasma-Bitters":{color:"#8b49ff",unlock:3},"Kokos-Creme":{color:"#fff0d8",unlock:2},"Salzlösung":{color:"#dce8ef",unlock:2}
};
const recipes=[
 {id:"neon-rain",name:"Neon Rain",ice:"Eiswürfel",glass:"highball",base:14,unlock:1,ingredients:{"Synthetischer Gin":45,"Blue Curaçao":20,"Limettensaft":15,"Tonic":60}},
 {id:"chrome-kiss",name:"Chrome Kiss",ice:"Crushed Ice",glass:"rocks",base:16,unlock:1,ingredients:{"Wodka":40,"Kirschlikör":20,"Limettensaft":20,"Neon-Sirup":10}},
 {id:"blackout",name:"Blackout Protocol",ice:"Kein Eis",glass:"rocks",base:18,unlock:1,ingredients:{"Dark Rum":50,"Kaffee-Likör":25,"Neon-Sirup":5}},
 {id:"data-mule",name:"Data Mule",ice:"Eiswürfel",glass:"highball",base:13,unlock:1,ingredients:{"Wodka":45,"Limettensaft":20,"Ginger Synth":70}},
 {id:"velvet",name:"Velvet Circuit",ice:"Crushed Ice",glass:"highball",base:17,unlock:1,ingredients:{"Synthetischer Gin":35,"Kirschlikör":25,"Tonic":50,"Neon-Sirup":10}},
 {id:"ghost",name:"Ghost in the Glass",ice:"Kein Eis",glass:"coupe",base:20,unlock:2,ingredients:{"Synthetischer Gin":40,"Orangenlikör":20,"Zitronensaft":20,"Salzlösung":5}},
 {id:"afterburner",name:"Afterburner",ice:"Eiswürfel",glass:"rocks",base:19,unlock:2,ingredients:{"Bourbon":50,"Ananassaft":30,"Zitronensaft":15,"Neon-Sirup":5}},
 {id:"pink-noise",name:"Pink Noise",ice:"Crushed Ice",glass:"highball",base:18,unlock:2,ingredients:{"Wodka":35,"Cranberry":50,"Kokos-Creme":25,"Soda":30}},
 {id:"zero-day",name:"Zero Day",ice:"Kein Eis",glass:"coupe",base:23,unlock:3,ingredients:{"Dark Rum":35,"Kaffee-Likör":20,"Rauchessenz":5,"Plasma-Bitters":5,"Neon-Sirup":5}},
 {id:"corporate",name:"Corporate Sunset",ice:"Eiswürfel",glass:"rocks",base:22,unlock:3,ingredients:{"Bourbon":45,"Orangenlikör":20,"Ananassaft":25,"Plasma-Bitters":5}},
 {id:"memory",name:"Memory Leak",ice:"Crushed Ice",glass:"highball",base:21,unlock:3,ingredients:{"Synthetischer Gin":40,"Cranberry":35,"Limettensaft":15,"Rauchessenz":5,"Soda":45}},
 {id:"last-call",name:"The Last Call",ice:"Kein Eis",glass:"coupe",base:30,unlock:5,ingredients:{"Bourbon":35,"Dark Rum":25,"Kirschlikör":15,"Plasma-Bitters":5,"Rauchessenz":5}}
];
const guestDefs=[
 {id:"nyx",name:"Nyx Vale",type:"Netzläuferin",initial:"N",theme:"cyan",mood:"Wachsam. Ihre Finger trommeln einen verschlüsselten Rhythmus.",favorite:"Chrome Kiss",romance:true,
  intro:["Du bist neu hinter diesem Tresen. Hoffentlich nicht neu im Schweigen.","Die Leitungen draußen summen heute anders. Hast du das auch bemerkt?","Ich brauche einen Drink und fünf Minuten, in denen niemand existiert."],
  choices:[
   {text:"Schweigen kostet nichts. Gute Drinks schon.",trust:2,chem:0,reply:"Pragmatisch. Damit kann ich arbeiten."},
   {text:"Für dich halte ich sogar die Überwachungskameras an.",trust:1,chem:3,flirt:true,reply:"Große Geste. Hoffentlich weißt du, wo der Netzstecker ist."},
   {text:"Sag mir, vor wem du wegläufst.",trust:-2,chem:0,risky:true,reply:"Und schon war die Stille vorbei."}],
  events:[{minTrust:4,text:"Nyx übergibt dir einen verschlüsselten Chip. Ein Rezept wird früher freigeschaltet.",effect:"unlock"},{minChem:5,text:"Nyx bleibt nach Ladenschluss. Ihr teilt einen selten ehrlichen Moment.",effect:"romance"},{text:"Eine Patrouillendrohne scannt die Bar. Nyx stört das Signal – Ruf +1.",effect:"rep"}]},
 {id:"mara",name:"Mara Voss",type:"Straßenmechanikerin",initial:"M",theme:"red",mood:"Öl an den Händen, Funken im Lächeln.",favorite:"Data Mule",romance:true,
  intro:["Mein Bike explodiert weniger oft als meine Beziehungen. Etwas Kühles?","Sag mir, dass du einen Schraubenschlüssel und einen Data Mule hast.","Zwölf Stunden unter einem Reaktor. Jetzt brauche ich etwas, das zurückbeißt."],
  choices:[{text:"Ich stabilisiere erst deinen Abend, dann dein Bike.",trust:2,chem:1,reply:"Selbstbewusst. Du darfst anfangen."},{text:"Ich mixe besser, als deine Ex kommuniziert.",trust:1,chem:3,flirt:true,reply:"Okay. Der Punkt geht an dich."},{text:"Explodierende Fahrzeuge bleiben draußen.",trust:0,chem:-1,reply:"Langweiler. Aber vernünftiger Langweiler."}],
  events:[{minTrust:4,text:"Mara kalibriert deinen Ausgießer. Die nächsten drei Drinks erhalten einen Präzisionsbonus.",effect:"precision"},{minChem:6,text:"Mara ritzt ihre Nummer in eine Metallserviette.",effect:"romance"},{text:"Mara bezahlt mit Ersatzteilen. Du erhältst 15,00 € Gegenwert.",effect:"money15"}]},
 {id:"iris",name:"IRIS-7",type:"Empathie-Androidin",initial:"7",theme:"cyan",mood:"Perfekte Haltung. Unperfekt neugieriger Blick.",favorite:"Velvet Circuit",romance:true,
  intro:["Ich untersuche menschliche Nähe. Ein Drink scheint statistisch hilfreich.","Ist Flirten eine Dienstleistung oder ein Fehler im Protokoll?","Heute möchte ich etwas erleben, das nicht in meinen Trainingsdaten steht."],
  choices:[{text:"Beides. Deshalb macht es Spaß.",trust:2,chem:2,reply:"Widerspruch akzeptiert. Interesse steigt."},{text:"Mit der richtigen Person ist es Forschung zu zweit.",trust:1,chem:3,flirt:true,reply:"Antrag auf Feldstudie registriert."},{text:"Androiden zahlen im Voraus.",trust:-1,chem:0,reply:"Vorurteil erkannt. Zahlung dennoch autorisiert."}],
  events:[{minTrust:5,text:"IRIS scannt dein Lager und optimiert die Kühlung. Alle Vorräte +25 ml.",effect:"stock"},{minChem:6,text:"IRIS fragt, ob Erinnerungen auch echt sind, wenn man sie auswählt. Du antwortest nicht sofort.",effect:"romance"},{text:"IRIS überweist 12,00 € als ‚soziale Forschungsförderung‘.",effect:"money12"}]},
 {id:"kessler",name:"Adrian Kessler",type:"Konzernstratege",initial:"K",theme:"gold",mood:"Teurer Anzug. Teurere Sorgen.",favorite:"Blackout Protocol",romance:false,
  intro:["Etwas Starkes. Und keine Fragen.","Die Stadt ist ein Vertrag, den niemand gelesen hat.","Ich bezahle für Diskretion. Der Drink ist nur die Quittung."],
  choices:[{text:"Keine Fragen. Nur exakte Milliliter.",trust:2,chem:0,reply:"Endlich jemand mit Prinzipien."},{text:"Wer schweigt, hört mehr. Ich höre gut.",trust:1,chem:0,reply:"Dann hören Sie jetzt besser weg."},{text:"Diskretion hat heute Aufpreis.",trust:-1,chem:0,risky:true,reply:"Geschäftssinn oder Erpressung? Noch bin ich unentschlossen."}],
  events:[{minTrust:5,text:"Kessler bietet einen Firmenauftrag an. Die Basiszahlung dieser Nacht steigt.",effect:"corporate"},{text:"Kessler lässt eine schwarze Kreditmarke liegen: +18,00 €.",effect:"money18"},{text:"Ein Konzernagent beobachtet euch. Ruf -1, aber Kessler zahlt Gefahrenzulage.",effect:"dangerpay"}]},
 {id:"rook",name:"Rook Serrano",type:"Untergrundkurier",initial:"R",theme:"red",mood:"Nervös. Blickt alle zwölf Sekunden zur Tür.",favorite:"Neon Rain",romance:true,
  intro:["Wenn jemand fragt: Ich war nie hier.","Ich brauche einen Drink, bevor die Drohnen mich triangulieren.","Keine Namen, keine Fotos, viel Eis."],
  choices:[{text:"Unsichtbare Gäste zahlen im Voraus.",trust:2,chem:0,reply:"Fair. Mit Gefahrenzulage."},{text:"Vielleicht will ich dich ja wiedersehen.",trust:1,chem:3,flirt:true,reply:"Falls ich morgen noch existiere."},{text:"Die Hintertür kostet extra.",trust:0,chem:-1,reply:"Alles kostet extra in dieser Stadt."}],
  events:[{minTrust:4,text:"Rook nennt dir einen sicheren Lieferweg. Shoppreise sind bis Schichtende 15 % niedriger.",effect:"discount"},{minChem:6,text:"Rook nimmt kurz die Maske ab. Nur für dich.",effect:"romance"},{text:"Eine Drohne streift das Fenster. Du verlierst 15 ml einer zufälligen Zutat.",effect:"loss"}]},
 {id:"sol",name:"Dr. Sol Amani",type:"Neurochirurgin",initial:"S",theme:"gold",mood:"Ruhige Stimme. Hände, die heute zu viel gesehen haben.",favorite:"Ghost in the Glass",romance:true,unlock:2,
  intro:["Ich brauche etwas Klares. Mein Kopf ist voll genug.","Manche Erinnerungen sollte man nicht reparieren.","Heute habe ich einem Menschen sein Lächeln zurückgegeben. Ich habe meins verloren."],
  choices:[{text:"Dann leihe ich dir meins für einen Drink.",trust:1,chem:3,flirt:true,reply:"Vorsicht. Ich könnte es behalten."},{text:"Hier musst du niemanden retten.",trust:3,chem:0,reply:"Das ist seltener, als du denkst."},{text:"Klar kostet bei uns extra.",trust:-1,chem:0,reply:"Zynismus als Hausmarke. Verstanden."}],
  events:[{minTrust:5,text:"Sol behandelt deine überlasteten Implantate. Dein Ruf steigt um 2.",effect:"rep2"},{minChem:6,text:"Sol bleibt bis zum Morgen und erzählt von einem Leben außerhalb der Stadt.",effect:"romance"},{text:"Sol hinterlässt ein medizinisches Kühlmodul. Vorräte +40 ml.",effect:"stock40"}]},
 {id:"vega",name:"Vega Knox",type:"Club-Ikone",initial:"V",theme:"pink",mood:"Holografisches Make-up. Die ganze Bar schaut zu.",favorite:"Pink Noise",romance:true,unlock:2,
  intro:["Überrasch mich. Aber nicht langweilig.","Mein Feed sagt, diese Bar sei authentisch. Beweise es.","Ich brauche etwas, das auf Kamera gefährlich aussieht."],
  choices:[{text:"Authentizität ist nicht fotogen.",trust:2,chem:0,reply:"Gut. Du hast Rückgrat."},{text:"Du bist schon gefährlich genug. Der Drink darf charmant sein.",trust:0,chem:3,flirt:true,reply:"Das kommt in die engere Auswahl."},{text:"Für Reichweite gibt es keinen Rabatt.",trust:1,chem:-1,reply:"Endlich sagt es mal jemand."}],
  events:[{minTrust:4,text:"Vega erwähnt deine Bar im Stream. Ruf +3.",effect:"rep3"},{minChem:6,text:"Vega schaltet die Kameras aus. Das Gespräch wird plötzlich echt.",effect:"romance"},{text:"Fans bestellen virtuell Drinks für Vega. +20,00 €.",effect:"money20"}]},
 {id:"brass",name:"Brass Okoro",type:"Gang-Unterhändler",initial:"B",theme:"gold",mood:"Breite Schultern. Höflichkeit wie eine entsicherte Waffe.",favorite:"Afterburner",romance:false,unlock:2,
  intro:["Deine Bar steht auf neutralem Boden. Sorge dafür, dass es so bleibt.","Ich trinke nur, wenn ich dem Barkeeper vertraue.","Heute wird jemand eine schlechte Entscheidung treffen. Vielleicht bin ich es."],
  choices:[{text:"Neutralität beginnt mit derselben Rechnung für alle.",trust:3,chem:0,reply:"Das war die richtige Antwort."},{text:"Vertrauen wächst langsam. Bourbon wirkt schneller.",trust:1,chem:0,reply:"Praktischer Mensch."},{text:"Drohungen kosten Korkgeld.",trust:-2,chem:0,risky:true,reply:"Mut ist nicht dasselbe wie Klugheit."}],
  events:[{minTrust:5,text:"Brass erklärt die Bar zum geschützten Ort. Ruf +2 und Shoprabatt.",effect:"protection"},{text:"Ein Bote bezahlt Brass' Rechnung und lässt 16,00 € Trinkgeld da.",effect:"money16"},{text:"Eine rivalisierende Gang markiert die Tür. Ruf -1.",effect:"repdown"}]},
 {id:"lumen",name:"Lumen",type:"Straßenpoetin",initial:"L",theme:"pink",mood:"Nasse Haare, billiger Mantel, unbezahlbare Worte.",favorite:"Memory Leak",romance:true,unlock:3,
  intro:["Die Stadt regnet heute in Moll.","Kann ein Drink eine Erinnerung ersetzen?","Ich schreibe über Leute, die nachts so tun, als wären sie frei."],
  choices:[{text:"Nur schlechte Erinnerungen. Gute bleiben kleben.",trust:2,chem:1,reply:"Das schreibe ich mir nicht auf. Das behalte ich."},{text:"Ich könnte dir einen besseren Reim anbieten.",trust:0,chem:3,flirt:true,reply:"Dann reim dich mal in mein Herz."},{text:"Gedichte zahlen keine Miete.",trust:-2,chem:-1,reply:"Miete schreibt auch keine Gedichte."}],
  events:[{minTrust:5,text:"Lumen schreibt ein Gedicht über die Bar. Ruf +3.",effect:"rep3"},{minChem:6,text:"Lumen schenkt dir eine Zeile, die nur für dich bestimmt ist.",effect:"romance"},{text:"Ein Sammler kauft Lumens Servietten-Gedicht: Dein Anteil 14,00 €.",effect:"money14"}]},
 {id:"unit12",name:"UNIT-12",type:"Sicherheitsdrohne",initial:"12",theme:"red",mood:"Offiziell außer Dienst. Inoffiziell sehr durstig.",favorite:"Zero Day",romance:false,unlock:3,
  intro:["Bürger, Ihre Lizenzprüfung ist zufällig und vollkommen freiwillig.","Mein Ethikmodul meldet Überhitzung. Kühlmittel erbeten.","Ich habe heute 43 Straftaten ignoriert. Neuer Rekord."],
  choices:[{text:"Ein Drink gegen eine bestandene Prüfung.",trust:1,chem:0,risky:true,reply:"Korruption erkannt. Humor ebenfalls."},{text:"Hier bist du Gast, nicht Behörde.",trust:3,chem:0,reply:"Rollenwechsel akzeptiert."},{text:"Metall zahlt doppelt.",trust:-1,chem:0,reply:"Diskriminierungsprotokoll geöffnet."}],
  events:[{minTrust:5,text:"UNIT-12 löscht eine offene Lizenzstrafe. Du sparst 25,00 €.",effect:"money25"},{text:"UNIT-12 meldet die Bar als sicher. Ruf +2.",effect:"rep2"},{text:"Ein Diagnosefehler leert 20 ml Tonic auf den Boden.",effect:"tonicloss"}]}
];
const shopItems=[
 {id:"jigger",name:"Smart-Jigger",desc:"Messfehler zählen 25 % weniger stark.",price:60,kind:"upgrade"},
 {id:"shelves",name:"Kühlregal MK II",desc:"Maximalvorrat +150 ml; sofortige Auffüllung.",price:95,kind:"upgrade"},
 {id:"charisma",name:"Empathie-Implantat",desc:"Positive Dialogwerte erhalten +1 Vertrauen.",price:110,kind:"upgrade"},
 {id:"glassware",name:"Hologlas-Set",desc:"Basiszahlung jedes Drinks +15 %.",price:140,kind:"upgrade"},
 {id:"scanner",name:"Geschmacksscanner",desc:"Zeigt vor dem Servieren eine grobe Qualitätsprognose.",price:175,kind:"upgrade"},
 {id:"security",name:"Störsender",desc:"Negative Zufallsereignisse treten seltener auf.",price:210,kind:"upgrade"},
 {id:"stock",name:"Zutatenlieferung",desc:"Alle freigeschalteten Zutaten +100 ml.",price:38,kind:"consumable"},
 {id:"advert",name:"Neon-Werbung",desc:"Sofort +2 Ruf.",price:55,kind:"consumable"}
];
const achievements=[
 {id:"first",name:"Erster Ausschank",desc:"Serviere deinen ersten Drink.",icon:"🍸",test:s=>s.totalServed>=1},
 {id:"perfect",name:"Auf den Milliliter",desc:"Erreiche 100 % Mixqualität.",icon:"◎",test:s=>s.perfectDrinks>=1},
 {id:"social",name:"Stammgast",desc:"Erreiche Vertrauen 6 bei einem Kontakt.",icon:"◆",test:s=>Object.values(s.relationships).some(r=>r.trust>=6)},
 {id:"romance",name:"Neonherz",desc:"Erlebe einen romantischen Moment.",icon:"♥",test:s=>s.romances>=1},
 {id:"rich",name:"Schwarze Zahlen",desc:"Besitze mindestens 250,00 €.",icon:"€",test:s=>s.money>=250},
 {id:"legend",name:"Legende des District 9",desc:"Erreiche Ruf 20.",icon:"★",test:s=>s.reputation>=20},
 {id:"collector",name:"Vollausstattung",desc:"Besitze alle permanenten Upgrades.",icon:"▣",test:s=>shopItems.filter(i=>i.kind==="upgrade").every(i=>s.owned.includes(i.id))},
 {id:"survivor",name:"Sieben Nächte",desc:"Erreiche Nacht 7.",icon:"☾",test:s=>s.night>=7}
];
const defaultState=()=>({version:2,money:35,reputation:0,night:1,time:1200,servedTonight:0,earnedTonight:0,totalServed:0,perfectDrinks:0,romances:0,currentGuestId:null,dialogueDone:false,orderKnown:false,mixed:{},pourHistory:[],ice:"Kein Eis",pourStep:10,inventory:Object.fromEntries(Object.keys(ingredients).map(n=>[n,300])),owned:[],relationships:{},unlockedTier:1,eventLog:[],discount:false,precisionCharges:0,corporateBonus:false,audio:true,introSeen:false,achievements:[],storyFlags:{},guestBag:[]});
let state=defaultState();
let audioCtx=null;
function ensureRel(id){if(!state.relationships[id])state.relationships[id]={trust:0,chem:0,visits:0,romance:false};return state.relationships[id]}
function maxStock(){return state.owned.includes("shelves")?450:300}
function currentGuest(){return guestDefs.find(g=>g.id===state.currentGuestId)||null}
function currentRecipe(){const g=currentGuest();return g?recipes.find(r=>r.name===g.favorite):null}
function addLog(text){state.eventLog.push({t:formatClock(state.time),text});state.eventLog=state.eventLog.slice(-18);renderLog()}
function formatClock(min){let m=min%(24*60);return `${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}
function toast(text,bad=false){const el=document.createElement("div");el.className="toast"+(bad?" bad":"");el.textContent=text;$("toastHost").append(el);setTimeout(()=>el.remove(),2300)}
function beep(kind="tap"){if(!state.audio)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.type=kind==="good"?"sine":kind==="bad"?"sawtooth":"triangle";o.frequency.value=kind==="good"?620:kind==="bad"?150:290;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.12);o.start();o.stop(audioCtx.currentTime+.13)}catch(e){}}
function save(silent=true){localStorage.setItem("neonLastCallDeluxe",JSON.stringify(state));if(!silent)toast("Spielstand lokal gespeichert.")}
function load(){try{const raw=localStorage.getItem("neonLastCallDeluxe");if(raw)state={...defaultState(),...JSON.parse(raw)};}catch(e){state=defaultState()}renderAll();if(!state.introSeen)$("introDialog").showModal()}
function availableGuests(){return guestDefs.filter(g=>(g.unlock||1)<=state.unlockedTier)}
function refillGuestBag(){state.guestBag=availableGuests().map(g=>g.id);for(let i=state.guestBag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[state.guestBag[i],state.guestBag[j]]=[state.guestBag[j],state.guestBag[i]]}}
function nextGuest(){if(state.servedTonight>=nightGoal().guests)return endNight();if(!state.guestBag.length)refillGuestBag();let id=state.guestBag.pop();if(id===state.currentGuestId&&state.guestBag.length)id=state.guestBag.pop();state.currentGuestId=id;state.dialogueDone=false;state.orderKnown=false;state.mixed={};state.pourHistory=[];state.ice="Kein Eis";const rel=ensureRel(id);rel.visits++;state.time+=20;const g=currentGuest();addLog(`${g.name} betritt die Bar.`);renderAll();beep()}
function renderGuest(){const g=currentGuest();if(!g){$("portrait").innerHTML="<span>?</span>";$("portrait").removeAttribute("data-theme");$("guestName").textContent="Die Bar wartet";$("guestType").textContent="Kein Gast";$("guestMood").textContent="Saurer Regen läuft über die Scheiben.";$("dialogue").textContent=state.servedTonight?"Der nächste Gast wartet draußen.":"Beginne die Schicht.";$("choices").innerHTML="";$("nextGuestBtn").textContent=state.servedTonight?"Nächster Gast":"Schicht beginnen";$("nextGuestBtn").classList.remove("hidden");$("talkAgainBtn").classList.add("hidden");updateMeters(null);return}
 const rel=ensureRel(g.id);$("portrait").innerHTML=`<span>${g.initial}</span>`;$("portrait").dataset.theme=g.theme;$("guestName").textContent=g.name;$("guestType").textContent=g.type;$("guestMood").textContent=g.mood;$("relationshipBadge").textContent=relationshipName(rel);updateMeters(rel);$("nextGuestBtn").classList.add("hidden");
 if(!state.dialogueDone){$("dialogue").textContent=g.intro[(rel.visits-1)%g.intro.length];renderChoices(g)}else{$("dialogue").textContent=state.lastReply||`${g.name} wartet auf den Drink.`;$("choices").innerHTML="";$("talkAgainBtn").classList.toggle("hidden",state.orderKnown)}
}
function relationshipName(r){if(r.romance)return"Vertraut ♥";if(r.trust>=7)return"Verbündet";if(r.chem>=6)return"Spürbare Chemie";if(r.trust>=4)return"Bekannt";if(r.trust<0)return"Misstrauisch";return"Unbekannt"}
function updateMeters(r){const t=r?clamp(r.trust,-5,10):0,c=r?clamp(r.chem,-5,10):0;$("trustValue").textContent=t;$("chemistryValue").textContent=c;$("trustBar").style.width=`${clamp((t+5)/15*100,0,100)}%`;$("chemistryBar").style.width=`${clamp((c+5)/15*100,0,100)}%`}
function renderChoices(g){$("choices").innerHTML="";g.choices.forEach(c=>{const b=document.createElement("button");b.className="choice"+(c.flirt?" flirt":"")+(c.risky?" risky":"");b.textContent=c.text;b.onclick=()=>chooseDialogue(c);$("choices").append(b)})}
function chooseDialogue(c){const g=currentGuest(),r=ensureRel(g.id);let trust=c.trust,chem=c.chem;if(state.owned.includes("charisma")&&trust>0)trust++;r.trust=clamp(r.trust+trust,-5,10);r.chem=clamp(r.chem+chem,-5,10);state.dialogueDone=true;state.orderKnown=true;state.lastReply=c.reply;addLog(`${g.name}: Bestellung ${g.favorite}.`);renderAll();beep(c.trust<0?"bad":"good")}
function renderOrder(){const r=currentRecipe();$("orderName").textContent=state.orderKnown&&r?r.name:"—";$("orderHint").textContent=state.orderKnown?"Rezept im Tablet prüfen und exakt mischen.":currentGuest()?"Wähle zuerst eine Antwort.":"Noch keine Bestellung.";$("glassLabel").textContent=r?({highball:"Highball",rocks:"Tumbler",coupe:"Coupette"}[r.glass]):"Highball";$("glass").className=`glass ${r?r.glass:"highball"}`}
function renderIngredients(){const root=$("ingredients");root.innerHTML="";Object.entries(ingredients).forEach(([name,meta])=>{const unlocked=meta.unlock<=state.unlockedTier,stock=state.inventory[name]||0;const el=document.createElement("button");el.className="ingredient"+(unlocked?"":" locked");el.disabled=!unlocked;el.innerHTML=`<div class="name">${name}</div><div class="stock">${stock} ml · +${state.pourStep} ml</div><div class="bar"><i style="width:${clamp(stock/maxStock()*100,0,100)}%"></i></div>`;el.onclick=()=>pour(name);root.append(el)})}
function pour(name){if(!state.orderKnown)return toast("Zuerst die Bestellung aufnehmen.",true);const ml=state.pourStep;if((state.inventory[name]||0)<ml)return toast("Nicht genug Vorrat.",true);state.inventory[name]-=ml;state.mixed[name]=(state.mixed[name]||0)+ml;state.pourHistory.push({name,ml});renderMix();renderIngredients();beep()}
function undo(){const p=state.pourHistory.pop();if(!p)return;state.mixed[p.name]-=p.ml;if(state.mixed[p.name]<=0)delete state.mixed[p.name];state.inventory[p.name]+=p.ml;renderMix();renderIngredients()}
function clearGlass(refund=true){if(refund)Object.entries(state.mixed).forEach(([n,v])=>state.inventory[n]=(state.inventory[n]||0)+v);state.mixed={};state.pourHistory=[];state.ice="Kein Eis";renderAll()}
function renderMix(){const total=Object.values(state.mixed).reduce((a,b)=>a+b,0);$("totalMl").textContent=total;$("liquid").style.height=`${clamp(total/180*100,0,100)}%`;$("iceVisual").textContent=state.ice==="Eiswürfel"?"◇  ◇\n  ◇":state.ice==="Crushed Ice"?"✦✧✦\n✧✦✧":"";$("mixLog").innerHTML=Object.keys(state.mixed).length?Object.entries(state.mixed).map(([n,v])=>`<div>${n}: <strong>${v} ml</strong></div>`).join(""):"Das Glas ist leer.";$("pourStep").textContent=`${state.pourStep} ml`;document.querySelectorAll("[data-step]").forEach(b=>b.classList.toggle("active",+b.dataset.step===state.pourStep));document.querySelectorAll("[data-ice]").forEach(b=>b.classList.toggle("active",b.dataset.ice===state.ice));$("undoBtn").disabled=!state.pourHistory.length;$("resetBtn").disabled=!state.pourHistory.length;$("serveBtn").disabled=!state.orderKnown||!state.pourHistory.length;
 if(state.owned.includes("scanner")&&state.pourHistory.length){const q=scoreDrink(currentRecipe()).score;$("mixLog").insertAdjacentHTML("beforeend",`<div style="margin-top:6px;color:var(--cyan)">Scanner-Prognose: ${q>=90?"exzellent":q>=70?"gut":q>=50?"instabil":"kritisch"}</div>`)} }
function scoreDrink(recipe){let error=0,targetTotal=0;const names=new Set([...Object.keys(recipe.ingredients),...Object.keys(state.mixed)]);for(const n of names){const target=recipe.ingredients[n]||0,actual=state.mixed[n]||0;error+=Math.abs(target-actual);targetTotal+=target}let ingredient=clamp(100-error/Math.max(targetTotal,1)*100,0,100);if(state.owned.includes("jigger"))ingredient=100-(100-ingredient)*.75;if(state.precisionCharges>0)ingredient=100-(100-ingredient)*.7;const ice=state.ice===recipe.ice?100:35;const score=Math.round(ingredient*.88+ice*.12);return{score,ingredient:Math.round(ingredient),ice}}
function serve(){const recipe=currentRecipe(),g=currentGuest(),rel=ensureRel(g.id),sc=scoreDrink(recipe);let base=recipe.base*(state.owned.includes("glassware")?1.15:1)*(state.corporateBonus?1.12:1);let social=1+Math.max(0,rel.trust)*.025+Math.max(0,rel.chem)*.02;let tip=base*(sc.score/100)*(0.1+Math.max(0,rel.trust)*.025+Math.max(0,rel.chem)*.035);if(rel.trust<0)tip*=.4;const pay=base*social,earned=pay+tip;state.money+=earned;state.earnedTonight+=earned;state.totalServed++;state.servedTonight++;state.time+=45;if(sc.score===100)state.perfectDrinks++;if(state.precisionCharges>0)state.precisionCharges--;state.reputation+=sc.score>=95?2:sc.score>=75?1:sc.score<45?-1:0;const event=sc.score>=70?resolveEvent(g,rel):"Der Drink verfehlt sein Ziel. Der Gast bezahlt, aber das Gespräch endet früh.";addLog(`${g.name}: ${sc.score}% Qualität, ${moneyFmt.format(earned)}.`);showResult(sc,pay,tip,event);state.currentGuestId=null;state.orderKnown=false;state.dialogueDone=false;state.mixed={};state.pourHistory=[];checkUnlocks();checkAchievements();save();renderAll()}
function resolveEvent(g,rel){let pool=g.events.filter(e=>(!e.minTrust||rel.trust>=e.minTrust)&&(!e.minChem||rel.chem>=e.minChem));if(state.owned.includes("security"))pool=pool.filter(e=>!["loss","repdown","tonicloss"].includes(e.effect)).concat(pool.filter(e=>!["loss","repdown","tonicloss"].includes(e.effect)));const ev=pool[Math.floor(Math.random()*pool.length)]||g.events[g.events.length-1];applyEffect(ev.effect,g,rel);return ev.text}
function applyEffect(effect,g,rel){const addMoney=n=>{state.money+=n;state.earnedTonight+=n};if(effect==="unlock")state.unlockedTier=Math.max(state.unlockedTier,2);if(effect==="romance"&&!rel.romance){rel.romance=true;state.romances++}if(effect==="rep")state.reputation++;if(effect==="rep2")state.reputation+=2;if(effect==="rep3")state.reputation+=3;if(effect==="repdown")state.reputation--;if(effect==="precision")state.precisionCharges+=3;if(effect==="stock")Object.keys(ingredients).forEach(n=>state.inventory[n]=Math.min(maxStock(),state.inventory[n]+25));if(effect==="stock40")Object.keys(ingredients).forEach(n=>state.inventory[n]=Math.min(maxStock(),state.inventory[n]+40));if(effect==="money12")addMoney(12);if(effect==="money14")addMoney(14);if(effect==="money15")addMoney(15);if(effect==="money16")addMoney(16);if(effect==="money18")addMoney(18);if(effect==="money20")addMoney(20);if(effect==="money25")addMoney(25);if(effect==="dangerpay"){addMoney(10);state.reputation--}if(effect==="corporate")state.corporateBonus=true;if(effect==="discount")state.discount=true;if(effect==="protection"){state.reputation+=2;state.discount=true}if(effect==="loss"){const n=Object.keys(ingredients)[Math.floor(Math.random()*Object.keys(ingredients).length)];state.inventory[n]=Math.max(0,state.inventory[n]-15)}if(effect==="tonicloss")state.inventory["Tonic"]=Math.max(0,state.inventory["Tonic"]-20)}
function showResult(sc,pay,tip,event){$("resultTitle").textContent=sc.score>=95?"Meisterhaft serviert":sc.score>=80?"Sauber gemixt":sc.score>=60?"Akzeptabel":"Missglückt";$("resultBody").innerHTML=`<div class="score-ring" style="--score:${sc.score*3.6}deg"><strong>${sc.score}%</strong></div><div class="score-grid"><div><small>Rezepttreue</small><strong>${sc.ingredient}%</strong></div><div><small>Eis</small><strong>${sc.ice}%</strong></div><div><small>Verdient</small><strong>${moneyFmt.format(pay+tip)}</strong></div></div><p>Basis & Bonus: <strong>${moneyFmt.format(pay)}</strong><br>Trinkgeld: <strong>${moneyFmt.format(tip)}</strong></p><div class="event-card">${event}</div>`;$("resultDialog").showModal();beep(sc.score>=70?"good":"bad")}
function nightGoal(){return{guests:3+Math.min(3,Math.floor((state.night-1)/2)),money:45+(state.night-1)*14}}
function renderObjective(){const goal=nightGoal(),guestP=state.servedTonight/goal.guests,moneyP=state.earnedTonight/goal.money,p=Math.min(1,(guestP+moneyP)/2);$("objectiveText").textContent=`Serviere ${goal.guests} Gäste und verdiene ${moneyFmt.format(goal.money)}.`;$("objectiveBar").style.width=`${p*100}%`;$("objectiveProgressText").textContent=`${state.servedTonight}/${goal.guests} Gäste · ${moneyFmt.format(state.earnedTonight)}/${moneyFmt.format(goal.money)}`}
function endNight(){const goal=nightGoal(),success=state.earnedTonight>=goal.money;let bonus=success?15+state.night*3:0;if(success){state.money+=bonus;state.reputation++}$("nightTitle").textContent=`Nacht ${state.night} beendet`;$("nightBody").innerHTML=`<h3>${success?"Ziel erreicht":"Ziel verfehlt"}</h3><p>Du hast ${state.servedTonight} Gäste bedient und ${moneyFmt.format(state.earnedTonight)} verdient.</p>${success?`<div class="event-card">Schichtbonus: <strong>${moneyFmt.format(bonus)}</strong> · Ruf +1</div>`:`<div class="event-card">Kein Schichtbonus. Morgen wartet eine neue Chance.</div>`}`;$("nightDialog").showModal();save()}
function continueNight(){state.night++;state.servedTonight=0;state.earnedTonight=0;state.time=1200;state.discount=false;state.corporateBonus=false;state.currentGuestId=null;state.guestBag=[];Object.keys(ingredients).forEach(n=>{if(ingredients[n].unlock<=state.unlockedTier)state.inventory[n]=Math.min(maxStock(),state.inventory[n]+70)});checkUnlocks();$("nightDialog").close();addLog(`Nacht ${state.night} beginnt.`);renderAll();save()}
function checkUnlocks(){const old=state.unlockedTier;if(state.reputation>=5||state.night>=3)state.unlockedTier=Math.max(state.unlockedTier,2);if(state.reputation>=12||state.night>=5)state.unlockedTier=Math.max(state.unlockedTier,3);if(state.night>=7&&state.reputation>=18)state.unlockedTier=5;if(state.unlockedTier>old)toast(`Neue Zutaten und Gäste freigeschaltet: Stufe ${state.unlockedTier}!`)}
function checkAchievements(){achievements.forEach(a=>{if(!state.achievements.includes(a.id)&&a.test(state)){state.achievements.push(a.id);toast(`Erfolg freigeschaltet: ${a.name}`);addLog(`Erfolg: ${a.name}.`)}})}
function renderRecipes(filter=""){const list=$("recipeList"),items=recipes.filter(r=>r.name.toLowerCase().includes(filter.toLowerCase()));list.innerHTML=items.map(r=>{const locked=r.unlock>state.unlockedTier;return `<article class="recipe ${locked?"locked":""}"><header><div><div class="recipe-meta">${locked?`STUFE ${r.unlock} – GESPERRT`:({highball:"HIGHBALL",rocks:"TUMBLER",coupe:"COUPETTE"}[r.glass])}</div><h3>${r.name}</h3></div><span class="price">${moneyFmt.format(r.base)}</span></header><div class="muted">${r.ice}</div><ul>${Object.entries(r.ingredients).map(([n,v])=>`<li>${v} ml ${n}</li>`).join("")}</ul></article>`}).join("");$("recipeCount").textContent=`${items.length} Rezepte`}
function renderShop(){const list=$("shopList");list.innerHTML="";shopItems.forEach(item=>{const owned=state.owned.includes(item.id),price=Math.round(item.price*(state.discount?.85:1));const el=document.createElement("article");el.className="shop-item";el.innerHTML=`<div><div class="panel-label">${item.kind==="upgrade"?"UPGRADE":"VERBRAUCH"}</div><h3>${item.name}</h3><p>${item.desc}</p></div><footer><span class="price">${owned?"Installiert":moneyFmt.format(price)}</span><button class="button secondary" ${owned?"disabled":""}>${owned?"Aktiv":"Kaufen"}</button></footer>`;el.querySelector("button").onclick=()=>buy(item,price);list.append(el)})}
function buy(item,price){if(state.money<price)return toast("Nicht genug Credits.",true);state.money-=price;if(item.kind==="upgrade")state.owned.push(item.id);if(item.id==="shelves")Object.keys(ingredients).forEach(n=>state.inventory[n]+=150);if(item.id==="stock")Object.keys(ingredients).forEach(n=>{if(ingredients[n].unlock<=state.unlockedTier)state.inventory[n]=Math.min(maxStock(),state.inventory[n]+100)});if(item.id==="advert")state.reputation+=2;state.discount=false;checkAchievements();renderAll();renderShop();save();beep("good")}
function renderContacts(){const cards=guestDefs.map(g=>{const r=ensureRel(g.id),locked=(g.unlock||1)>state.unlockedTier;return `<article class="contact-card ${locked?"locked":""}"><div class="panel-label">${locked?"UNBEKANNT":g.type}</div><h3>${locked?"████ ████":g.name}</h3><p class="relation">${locked?"Noch nicht begegnet":relationshipName(r)}</p><div class="contact-stats"><span>Vertrauen ${r.trust}</span><span>Chemie ${r.chem}</span><span>Besuche ${r.visits}</span></div></article>`}).join("");$("contactList").innerHTML=cards;const known=guestDefs.filter(g=>ensureRel(g.id).visits>0).sort((a,b)=>ensureRel(b.id).trust-ensureRel(a.id).trust).slice(0,4);$("contactMini").innerHTML=known.length?known.map(g=>{const r=ensureRel(g.id);return `<div class="mini-contact"><span class="mini-avatar">${g.initial}</span><div>${g.name}<small>${relationshipName(r)}</small></div><strong>${r.trust}</strong></div>`}).join(""):"<p class='muted'>Noch keine Kontakte.</p>"}
function renderAchievements(){$("achievementList").innerHTML=achievements.map(a=>{const unlocked=state.achievements.includes(a.id);return `<article class="achievement ${unlocked?"unlocked":"locked"}"><div class="icon">${a.icon}</div><h3>${a.name}</h3><p>${a.desc}</p><strong>${unlocked?"Freigeschaltet":"Gesperrt"}</strong></article>`}).join("")}
function renderLog(){$("eventLog").innerHTML=state.eventLog.length?state.eventLog.slice().reverse().map(e=>`<p><time>${e.t}</time>${e.text}</p>`).join(""):"<p>System bereit.</p>"}
function renderStats(){$("money").textContent=moneyFmt.format(state.money);$("reputation").textContent=state.reputation;$("night").textContent=state.night;$("clock").textContent=formatClock(state.time);$("audioBtn").textContent=`♪ Sound: ${state.audio?"An":"Aus"}`}
function renderAll(){renderStats();renderGuest();renderOrder();renderIngredients();renderMix();renderObjective();renderLog();renderContacts();renderAchievements();renderRecipes();renderShop();checkAchievements()}
$("nextGuestBtn").onclick=nextGuest;$("talkAgainBtn").onclick=()=>{state.orderKnown=true;renderAll()};$("serveBtn").onclick=serve;$("undoBtn").onclick=undo;$("resetBtn").onclick=()=>clearGlass(true);$("continueNightBtn").onclick=continueNight;
document.querySelectorAll("[data-step]").forEach(b=>b.onclick=()=>{state.pourStep=+b.dataset.step;renderMix();renderIngredients()});document.querySelectorAll("[data-ice]").forEach(b=>b.onclick=()=>{state.ice=b.dataset.ice;renderMix();beep()});
$("recipeBtn").onclick=()=>{$("recipeDialog").showModal();renderRecipes()};$("shopBtn").onclick=()=>{$("shopDialog").showModal();renderShop()};$("contactsBtn").onclick=()=>{$("contactsDialog").showModal();renderContacts()};$("achievementsBtn").onclick=()=>{$("achievementsDialog").showModal();renderAchievements()};$("saveBtn").onclick=()=>save(false);$("audioBtn").onclick=()=>{state.audio=!state.audio;renderStats();save()};$("recipeSearch").oninput=e=>renderRecipes(e.target.value);
$("resetSaveBtn").onclick=()=>{if(confirm("Wirklich einen neuen Spielstand beginnen? Der aktuelle Fortschritt wird gelöscht.")){localStorage.removeItem("neonLastCallDeluxe");location.reload()}};
$("introStartBtn").onclick=()=>{state.introSeen=true;$("introDialog").close();addLog("Bar-System initialisiert.");save();renderAll()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
window.addEventListener("beforeunload",()=>save());load();
