'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#game'),ctx=canvas.getContext('2d');
const money=$('#money'),rep=$('#rep'),served=$('#served'),nightLabel=$('#nightLabel'),trustBar=$('#trustBar'),chemBar=$('#chemBar');
const dialogPanel=$('#dialogPanel'),mixPanel=$('#mixPanel'),dialogText=$('#dialogText'),choices=$('#choices'),speaker=$('#speaker');
const recipePanel=$('#recipePanel'),recipeName=$('#recipeName'),recipeMeta=$('#recipeMeta'),recipeIngredients=$('#recipeIngredients');
const ingredientRack=$('#ingredientRack'),volumeLabel=$('#volumeLabel'),shopPanel=$('#shopPanel'),shopItems=$('#shopItems');
const contactsPanel=$('#contactsPanel'),contactsList=$('#contactsList'),toastEl=$('#toast'),start=$('#start');
const recipeBtn=$('#recipeBtn'),resetBtn=$('#resetBtn'),iceBtn=$('#iceBtn'),crushedBtn=$('#crushedBtn'),shakeBtn=$('#shakeBtn'),serveBtn=$('#serveBtn');
const talkBtn=$('#talkBtn'),mixBtn=$('#mixBtn'),shopBtn=$('#shopBtn'),contactsBtn=$('#contactsBtn'),startBtn=$('#startBtn');
let W=0,H=0,dpr=1,last=0,time=0;
const SAVE='neon-last-call-visual-v1';
const ING={
 'Neon Gin':{c:'#33e7ff',price:2},'Void Vodka':{c:'#aab4ff',price:2},'Chrome Rum':{c:'#d99154',price:2},'Sakura Vermouth':{c:'#ff6da8',price:2},
 'Synth Lime':{c:'#72ff70',price:1},'Blood Orange':{c:'#ff4b27',price:1},'Blue Curaçao':{c:'#218cff',price:2},'Plasma Tonic':{c:'#b8fbff',price:1},
 'Cherry Bitters':{c:'#7b0824',price:1},'Ginger Spark':{c:'#ffd05c',price:1},'Coconut Milk':{c:'#fff7e8',price:2},'Espresso':{c:'#3a170e',price:1}
};
const RECIPES={
 'Electric Kiss':{glass:'coupe',ice:'none',shake:true,ing:{'Neon Gin':45,'Sakura Vermouth':20,'Synth Lime':15}},
 'Corporate Ghost':{glass:'rocks',ice:'cube',shake:false,ing:{'Void Vodka':50,'Plasma Tonic':80,'Cherry Bitters':5}},
 'Redline':{glass:'highball',ice:'crushed',shake:false,ing:{'Chrome Rum':40,'Blood Orange':45,'Ginger Spark':35}},
 'Blue Memory':{glass:'martini',ice:'none',shake:true,ing:{'Void Vodka':40,'Blue Curaçao':25,'Synth Lime':15}},
 'Midnight Protocol':{glass:'rocks',ice:'cube',shake:true,ing:{'Chrome Rum':35,'Espresso':30,'Coconut Milk':25}},
 'Glass Heart':{glass:'coupe',ice:'none',shake:true,ing:{'Neon Gin':35,'Sakura Vermouth':30,'Blood Orange':20}}
};
const GUESTS=[
 {name:'MIRA-7',role:'Kurierin',skin:'#f5a8ce',hair:'#141124',accent:'#ff2d9b',eye:'#ff277e',drink:'Electric Kiss',flirty:true,
 lines:['Du bist neu hinter diesem Tresen, oder?','Heute riecht die Stadt nach Ozon und Ärger.','Ich brauche etwas, das meine Hände ruhig hält.'],
 choices:[['Ich lerne schnell. Vor allem Gesichter.','flirt',5,8],['Was ist passiert?','kind',8,2],['Bestellung?','cold',-2,0]]},
 {name:'VALENCIA',role:'Netzläuferin',skin:'#e8a0c4',hair:'#16111e',accent:'#8c55ff',eye:'#ff1e78',drink:'Blue Memory',flirty:true,
 lines:['Mein Deck wurde fast gegrillt. Ich dagegen sehe noch fantastisch aus.','Kannst du einen Drink bauen, der schlechte Erinnerungen löscht?','Stell ihn auf den Tresen. Langsam.'],
 choices:[['Dein Aussehen überlebt offenbar jedes Systemversagen.','flirt',4,9],['Wer war hinter dir her?','kind',7,1],['Solange du bezahlst.','cold',-4,0]]},
 {name:'MR. KANE',role:'Konzernanwalt',skin:'#b98674',hair:'#d8d7e0',accent:'#44ddff',eye:'#7af8ff',drink:'Corporate Ghost',flirty:false,
 lines:['Diskretion ist in dieser Stadt die teuerste Zutat.','Ein Vertrag ist nur eine Drohung in höflicher Sprache.','Machen Sie mir den üblichen. Präzise.'],
 choices:[['Hier bleibt jedes Geheimnis im Glas.','kind',7,0],['Klingt, als hätten Sie Angst.','bold',2,0],['Bestellung verstanden.','cold',1,0]]},
 {name:'JUNO VEX',role:'Rockstar',skin:'#d89b8e',hair:'#ffedf6',accent:'#ff4d4d',eye:'#ffe36b',drink:'Redline',flirty:true,
 lines:['Die Menge draußen will Blut. Ich will nur etwas Lautes.','Deine Bar hat Stil. Du vielleicht auch.','Mach den Drink so wild wie die Nacht.'],
 choices:[['Ich kann beides liefern.','flirt',4,8],['Du wirkst erschöpft.','kind',8,2],['Nicht auf meinem Tresen randalieren.','bold',3,0]]},
 {name:'DR. SABLE',role:'Kybernetikerin',skin:'#80566d',hair:'#05050b',accent:'#54ffd1',eye:'#65ffd6',drink:'Midnight Protocol',flirty:false,
 lines:['Meine Implantate melden Stress. Unhöflich, aber korrekt.','Menschen vertrauen Maschinen mehr als einander. Faszinierend.','Ich benötige Koffein, Alkohol und Stille.'],
 choices:[['Maschinen brechen seltener Herzen.','bold',4,0],['Vielleicht fehlt ihnen nur die richtige Gesellschaft.','kind',7,2],['Midnight Protocol kommt.','cold',2,0]]},
 {name:'LUX',role:'Sängerin',skin:'#f2c3a2',hair:'#532348',accent:'#ffbd38',eye:'#8afcff',drink:'Glass Heart',flirty:true,
 lines:['Man sagt, du servierst Drinks, die Gefühle sichtbar machen.','Heute Abend singe ich für jemanden, der nicht kommen wird.','Gib mir etwas Schönes, bevor ich wieder lügen muss.'],
 choices:[['Dann sing heute Abend für mich.','flirt',5,10],['Du musst hier nichts vorspielen.','kind',9,3],['Ein Glass Heart also.','cold',1,0]]}
];
const state=Object.assign({money:120,rep:0,night:1,served:0,guestIndex:0,trust:{},chem:{},upgrades:{slowPour:0,biggerTips:0,iceSense:0},unlocked:Object.keys(ING)},JSON.parse(localStorage.getItem(SAVE)||'{}'));
let guest,phase='talk',lineIndex=0,mix={ing:{},ice:'none',shaken:false,volume:0,color:'#ffffff'},pouring=null,shakeT=0,serveAnim=0,particles=[];
function save(){localStorage.setItem(SAVE,JSON.stringify(state))} function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0)} addEventListener('resize',resize);resize();
function currentGuest(){return GUESTS[state.guestIndex%GUESTS.length]} function initGuest(){guest=currentGuest();state.trust[guest.name]??=0;state.chem[guest.name]??=0;lineIndex=0;phase='talk';$('#speaker').textContent=guest.name;renderDialog();updateHud()}
function updateHud(){money.textContent=state.money;rep.textContent=state.rep;served.textContent=state.served;nightLabel.textContent='Nacht '+state.night;trustBar.style.setProperty('--v',clamp(state.trust[guest?.name]||0,0,100)+'%');chemBar.style.setProperty('--v',clamp(state.chem[guest?.name]||0,0,100)+'%')}
function renderDialog(){if(!guest)return;dialogPanel.classList.remove('hidden');mixPanel.classList.add('hidden');phase='talk';dialogText.textContent=guest.lines[Math.min(lineIndex,guest.lines.length-1)];choices.innerHTML=''; if(lineIndex<guest.lines.length-1){guest.choices.forEach(([t,type,tr,ch])=>{let b=document.createElement('button');b.textContent=t;b.className=type==='flirt'?'flirt':'';b.onclick=()=>{state.trust[guest.name]=clamp(state.trust[guest.name]+tr,0,100);state.chem[guest.name]=clamp(state.chem[guest.name]+ch,0,100);lineIndex++;updateHud();renderDialog();save()};choices.append(b)})}else{let b=document.createElement('button');b.textContent=`${guest.drink} mixen`;b.onclick=openMix;choices.append(b)}}
function openMix(){phase='mix';dialogPanel.classList.add('hidden');mixPanel.classList.remove('hidden');resetMix(false);renderRack();showRecipe()}
function renderRack(){ingredientRack.innerHTML='';Object.entries(ING).forEach(([name,o])=>{let b=document.createElement('button');b.className='bottle-btn';b.style.setProperty('--c',o.c);b.innerHTML=`${name}<small>${mix.ing[name]||0} ml</small>`;let start=e=>{e.preventDefault();pouring=name};let stop=()=>pouring=null;b.addEventListener('pointerdown',start);b.addEventListener('pointerup',stop);b.addEventListener('pointercancel',stop);b.addEventListener('pointerleave',stop);ingredientRack.append(b)})}
function resetMix(toastIt=true){mix={ing:{},ice:'none',shaken:false,volume:0,color:'#ffffff'};pouring=null;shakeT=0;if(toastIt)toast('Glas geleert');renderRack();updateVolume()}
function updateVolume(){volumeLabel.textContent=Math.round(mix.volume)+' ml';$$('.bottle-btn').forEach((b,i)=>{let n=Object.keys(ING)[i];b.querySelector('small').textContent=(Math.round(mix.ing[n]||0))+' ml'})}
function addIngredient(name,amt){mix.ing[name]=(mix.ing[name]||0)+amt;mix.volume+=amt;mix.color=blendMix();updateVolume();for(let i=0;i<2;i++)particles.push({x:W*.5+(Math.random()-.5)*40,y:H*.47,vx:(Math.random()-.5)*.5,vy:1+Math.random(),life:1,c:ING[name].c})}
function hexRgb(h){let x=parseInt(h.slice(1),16);return[(x>>16)&255,(x>>8)&255,x&255]} function blendMix(){let total=0,r=0,g=0,b=0;for(const [n,v] of Object.entries(mix.ing)){let c=hexRgb(ING[n].c);total+=v;r+=c[0]*v;g+=c[1]*v;b+=c[2]*v}if(!total)return'#ffffff';return`rgb(${r/total|0},${g/total|0},${b/total|0})`}
function showRecipe(){let r=RECIPES[guest.drink];recipePanel.classList.remove('hidden');recipeName.textContent=guest.drink;recipeMeta.textContent=`Glas: ${r.glass} · Eis: ${r.ice==='cube'?'Eiswürfel':r.ice==='crushed'?'Crushed Ice':'ohne Eis'} · ${r.shake?'shaken':'nicht shaken'}`;recipeIngredients.innerHTML=Object.entries(r.ing).map(([n,v])=>`<li><b>${v} ml</b> ${n}</li>`).join('')}
function evaluate(){let r=RECIPES[guest.drink],err=0,target=0;for(const [n,v] of Object.entries(r.ing)){target+=v;err+=Math.abs((mix.ing[n]||0)-v)}for(const [n,v] of Object.entries(mix.ing))if(!r.ing[n])err+=v*1.5;let precision=clamp(1-err/(target*.85),0,1);let ice=mix.ice===r.ice?1:0;let shake=mix.shaken===r.shake?1:0;let score=Math.round((precision*.72+ice*.14+shake*.14)*100);let base=18+Math.round(target*.12),rel=(state.trust[guest.name]||0)*.08+(state.chem[guest.name]||0)*.1;let tip=Math.round((score/100)*(6+rel)*(1+state.upgrades.biggerTips*.15));let pay=base+tip;state.money+=pay;state.rep+=score>=90?3:score>=70?2:score>=45?1:-1;state.served++;state.trust[guest.name]=clamp(state.trust[guest.name]+Math.round(score/18)-2,0,100);if(guest.flirty&&score>85)state.chem[guest.name]=clamp(state.chem[guest.name]+3,0,100);save();return{score,pay,tip}}
function serve(){if(mix.volume<20)return toast('Das Glas ist noch fast leer.');serveAnim=1.25;phase='serve';mixPanel.classList.add('hidden');recipePanel.classList.add('hidden');let out=evaluate();setTimeout(()=>{dialogPanel.classList.remove('hidden');speaker.textContent=guest.name;let reaction=out.score>=95?'Perfekt. Du hast nicht nur das Rezept verstanden.':out.score>=80?'Sehr gut. Sauber gemixt.':out.score>=55?'Trinkbar. Beim nächsten Glas genauer.':'Das war… mutig. Nicht unbedingt gut.';dialogText.textContent=`${reaction} Qualität ${out.score} %. Bezahlung € ${out.pay}, davon € ${out.tip} Trinkgeld.`;choices.innerHTML='';let b=document.createElement('button');b.textContent='Nächsten Gast hereinlassen';b.onclick=nextGuest;choices.append(b);updateHud()},900)}
function nextGuest(){state.guestIndex++;if(state.served>=5){state.night++;state.served=0;state.money+=25;toast('Nacht abgeschlossen: € 25 Bonus')}save();initGuest()}
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>toastEl.classList.remove('show'),1700)}
function openShop(){shopPanel.classList.remove('hidden');shopItems.innerHTML='';const items=[['slowPour','Präzisionsausgießer','Einschenken 20 % langsamer',80],['biggerTips','Empathie-Chip','15 % mehr Trinkgeld',120],['iceSense','Thermalglas','Eisfehler werden milder bewertet',100]];for(const [id,n,d,c] of items){let lv=state.upgrades[id]||0,x=document.createElement('div');x.className='shop-item';x.innerHTML=`<b>${n} ${lv?`Lv.${lv}`:''}</b><small>${d}</small><button>${lv>=3?'MAX':'€ '+(c*(lv+1))}</button>`;x.querySelector('button').onclick=()=>{let p=c*(lv+1);if(lv>=3)return;if(state.money<p)return toast('Zu wenig Credits.');state.money-=p;state.upgrades[id]=lv+1;save();updateHud();openShop()};shopItems.append(x)}}
function openContacts(){contactsPanel.classList.remove('hidden');contactsList.innerHTML=GUESTS.map(g=>`<div class="contact-card"><b>${g.name}</b> · ${g.role}<br><small>Vertrauen ${state.trust[g.name]||0}</small> <span class="heart">Chemie ${state.chem[g.name]||0}</span></div>`).join('')}
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden')); recipeBtn.onclick=showRecipe;resetBtn.onclick=()=>resetMix();iceBtn.onclick=()=>{mix.ice='cube';toast('Eiswürfel hinzugefügt')};crushedBtn.onclick=()=>{mix.ice='crushed';toast('Crushed Ice hinzugefügt')};shakeBtn.onclick=()=>{if(mix.volume<10)return toast('Erst Zutaten einfüllen.');mix.shaken=true;shakeT=1.3;toast('Shaker aktiviert')};serveBtn.onclick=serve;talkBtn.onclick=renderDialog;mixBtn.onclick=openMix;shopBtn.onclick=openShop;contactsBtn.onclick=openContacts;
startBtn.onclick=()=>{start.style.display='none';initGuest()};
function neonLine(x1,y1,x2,y2,c,w=5){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.shadowColor=c;ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.shadowBlur=0}
function bg(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#08051c');g.addColorStop(.62,'#1a0d32');g.addColorStop(1,'#080611');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#100b24';ctx.fillRect(0,H*.12,W,H*.58);ctx.strokeStyle='rgba(132,83,200,.15)';for(let x=0;x<W;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+120,H*.3);ctx.stroke()}for(let y=0;y<H*.28;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}neonLine(0,H*.2,W*.22,H*.2,'#ff278f',6);neonLine(W*.36,H*.28,W*.84,H*.28,'#ff278f',5);neonLine(W*.38,H*.34,W*.86,H*.34,'#ff278f',5);neonLine(W*.72,0,W*.84,H*.14,'#45f6ff',4);ctx.fillStyle='rgba(10,7,22,.9)';ctx.fillRect(0,H*.60,W,H*.4);ctx.fillStyle='#2a122c';ctx.fillRect(0,H*.69,W,H*.31);let bar=ctx.createLinearGradient(0,H*.72,0,H);bar.addColorStop(0,'#7b315b');bar.addColorStop(.12,'#351329');bar.addColorStop(1,'#0a0711');ctx.fillStyle=bar;ctx.fillRect(0,H*.73,W,H*.27);ctx.fillStyle='rgba(255,100,190,.25)';ctx.fillRect(0,H*.73,W,3);}
function drawGuest(g,t){let cx=W*.5,base=H*.68,scale=Math.min(W/900,H/700);ctx.save();let bob=Math.sin(t*1.6)*3;ctx.translate(cx,base+bob);ctx.scale(scale,scale);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,10,170,22,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#20152d';ctx.beginPath();ctx.moveTo(-110,0);ctx.quadraticCurveTo(-105,-170,-64,-226);ctx.quadraticCurveTo(0,-270,64,-226);ctx.quadraticCurveTo(105,-170,110,0);ctx.fill();ctx.fillStyle=g.accent;ctx.globalAlpha=.45;ctx.fillRect(-100,-155,200,5);ctx.globalAlpha=1;ctx.fillStyle=g.skin;ctx.beginPath();ctx.ellipse(0,-185,62,76,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=g.hair;ctx.beginPath();ctx.ellipse(-4,-212,70,66,-.08,Math.PI,Math.PI*2);ctx.lineTo(50,-172);ctx.quadraticCurveTo(5,-197,-11,-157);ctx.quadraticCurveTo(-55,-166,-65,-204);ctx.fill();ctx.strokeStyle=g.eye;ctx.lineWidth=4;ctx.shadowColor=g.eye;ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(12,-190);ctx.lineTo(31,-191);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#8c3e68';ctx.lineWidth=2;ctx.beginPath();ctx.arc(9,-158,17,.25,2.4);ctx.stroke();ctx.fillStyle=g.skin;ctx.beginPath();ctx.roundRect(-110,-86,220,54,25);ctx.fill();ctx.strokeStyle=g.accent;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-92,-59);ctx.lineTo(-25,-48);ctx.moveTo(92,-59);ctx.lineTo(25,-48);ctx.stroke();ctx.fillStyle='#20232f';ctx.beginPath();ctx.roundRect(-112,-85,70,50,22);ctx.roundRect(42,-85,70,50,22);ctx.fill();ctx.restore();}
function drawGlass(){if(phase!=='mix'&&phase!=='serve')return;let x=W*.5,y=H*.56,sw=shakeT>0?Math.sin(time*28)*18:0;if(serveAnim>0)x+=(1-serveAnim/1.25)*W*.23;ctx.save();ctx.translate(x+sw,y);ctx.strokeStyle='rgba(220,248,255,.75)';ctx.lineWidth=3;ctx.shadowColor='#56eaff';ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(-55,-95);ctx.lineTo(-42,18);ctx.quadraticCurveTo(0,32,42,18);ctx.lineTo(55,-95);ctx.closePath();ctx.stroke();let max=110,fill=clamp(mix.volume/160,0,.92)*max;ctx.fillStyle=mix.color;ctx.globalAlpha=.82;ctx.beginPath();ctx.moveTo(-51,-91+max-fill);ctx.lineTo(51,-91+max-fill);ctx.lineTo(40,15);ctx.quadraticCurveTo(0,27,-40,15);ctx.closePath();ctx.fill();ctx.globalAlpha=.65;ctx.strokeStyle='#fff';if(mix.ice!=='none'){let count=mix.ice==='crushed'?12:4;for(let i=0;i<count;i++){let xx=((i*37)%74)-37,yy=-55+(i%4)*20;ctx.save();ctx.translate(xx,yy);ctx.rotate(i*.7);ctx.strokeRect(-8,-7,mix.ice==='crushed'?9:17,mix.ice==='crushed'?8:15);ctx.restore()}}ctx.restore();if(pouring){let c=ING[pouring].c;ctx.strokeStyle=c;ctx.lineWidth=7;ctx.shadowColor=c;ctx.shadowBlur=12;ctx.beginPath();ctx.moveTo(W*.5+55,H*.25);ctx.quadraticCurveTo(W*.55,H*.35,W*.5,H*.48);ctx.stroke();ctx.shadowBlur=0;}}
function drawParticles(dt){for(const p of particles){p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.life-=dt;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,3,8)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0)}
function loop(ts){let dt=Math.min((ts-last)/1000||0,.04);last=ts;time+=dt;if(pouring&&phase==='mix'){let speed=22*(1-state.upgrades.slowPour*.17);addIngredient(pouring,speed*dt)}if(shakeT>0)shakeT-=dt;if(serveAnim>0)serveAnim-=dt;bg();if(guest&&phase!=='mix'&&phase!=='serve')drawGuest(guest,time);drawGlass();drawParticles(dt);requestAnimationFrame(loop)}requestAnimationFrame(loop);
