const ingredients=[
{name:'Vodka',color:'#cbd7ef'},{name:'Gin',color:'#5d9d73'},{name:'Rum',color:'#9a4b2f'},{name:'Tequila',color:'#b87838'},{name:'Whiskey',color:'#8a3f1b'},{name:'Blue Curaçao',color:'#005bff'},{name:'Limettensaft',color:'#84b735'},{name:'Grenadine',color:'#d30b43'},{name:'Sirup',color:'#f7e4ec'}];
const recipes=[
{name:'Neon Reaper',ice:'crushed',parts:{Vodka:30,'Blue Curaçao':15,Limettensaft:10,Grenadine:5}},
{name:'Chrome Sunset',ice:'cubes',parts:{Tequila:30,Grenadine:10,Limettensaft:15,Sirup:5}},
{name:'Ghost Protocol',ice:'cubes',parts:{Gin:35,Vodka:10,Limettensaft:10,Sirup:5}},
{name:'Black Circuit',ice:'none',parts:{Whiskey:40,Rum:15,Sirup:5}}
];
const guests=[
{name:'Valencia',role:'Cybernetische Agentin',likes:'Starke Drinks, Ehrlichkeit, Nachtstadt',dislikes:'Lügen, billige Ausreden',heart:35,filter:'none',lines:['Die Nacht ist jung. Überrasche mich mit etwas Starkem.','Konzerne zahlen gut. Vertrauen kostet mehr.','Du wirkst heute ungewöhnlich konzentriert.']},
{name:'Mara Voss',role:'Datenbrokerin',likes:'Gin, Geheimnisse, Charme',dislikes:'Moralpredigten, Langeweile',heart:22,filter:'hue-rotate(28deg) saturate(1.2)',lines:['Ich brauche etwas Klares. Und eine Antwort.','Informationen sind wie Alkohol: falsch dosiert werden sie tödlich.']},
{name:'Jun Aras',role:'Konzernstratege',likes:'Whiskey, Präzision, Diskretion',dislikes:'Chaos, schlechte Manieren',heart:18,filter:'hue-rotate(170deg) contrast(1.1)',lines:['Ein sauberer Drink sagt viel über einen Menschen.','Heute Abend zählt jedes Detail.']}
];
let state=JSON.parse(localStorage.getItem('nlc-premium')||'null')||{cash:260,rep:35,night:1,earned:0,goal:400,guest:0,recipe:0,ice:'crushed',selected:0,step:5,mix:{},shaken:false,upgrades:{precision:0,tip:0}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('nlc-premium',JSON.stringify(state))}
function render(){
 $('#cash').textContent=state.cash.toLocaleString('de-DE'); $('#night').textContent=state.night; $('#repFill').style.width=Math.min(100,state.rep)+'%';
 $('#goalText').textContent=`Verdiene € ${state.goal}`; $('#goalProgress').textContent=`€ ${state.earned} / € ${state.goal}`;
 const g=guests[state.guest]; $('#guestName').textContent=g.name;$('#speaker').textContent=g.name;$('#guestRole').textContent=g.role;$('#likes').textContent=g.likes;$('#dislikes').textContent=g.dislikes;$('#heartFill').style.width=g.heart+'%';$('#heartValue').textContent=g.heart+'/100';$('#portrait').style.filter=g.filter;
 const r=recipes[state.recipe];$('#recipeName').textContent=r.name;$('#recipeIce').textContent=r.ice==='crushed'?'Crushed Ice':r.ice==='cubes'?'Eiswürfel':'Ohne Eis';$('#recipeLines').innerHTML=Object.entries(r.parts).map(([k,v])=>`<div><span>${k}</span><b>${v} ml</b></div>`).join('');
 $$('.icebox button').forEach(b=>b.classList.toggle('active',b.dataset.ice===state.ice));
 renderBottles(); renderChoices(); drawDrink(); drawRecipe(); save();
}
function renderBottles(){const root=$('#bottles');root.innerHTML='';ingredients.forEach((x,i)=>{const v=state.mix[x.name]||0;const el=document.createElement('div');el.className='bottle '+(i===state.selected?'active':'');el.style.setProperty('--c',x.color);el.innerHTML=`<div class="neck"></div><div class="body"></div><label>${x.name}</label><em>${v} ml</em>`;el.onclick=()=>{state.selected=i;renderBottles()};root.appendChild(el)})}
function renderChoices(){const g=guests[state.guest];$('#dialogText').textContent=g.lines[Math.floor(Math.random()*g.lines.length)];$('#choices').innerHTML='';[
['♥ Du bekommst heute genau, was du willst.',2,true],['Was führt dich in diese Gegend?',1,false],['Ein weiterer langer Tag?',0,false]
].forEach(([t,v,f])=>{let b=document.createElement('button');b.textContent=t;b.className=f?'flirt':'';b.onclick=()=>{g.heart=Math.min(100,g.heart+v+1);$('#dialogText').textContent=f?'Pass auf, Barkeeper. So fangen gefährliche Nächte an.':'Vielleicht erzähle ich es dir nach dem ersten Schluck.';render()};$('#choices').appendChild(b)})}
function mixColor(){let sum=0,r=0,g=0,b=0;ingredients.forEach(x=>{const v=state.mix[x.name]||0;if(v){const c=x.color.match(/[a-f\d]{2}/gi).map(h=>parseInt(h,16));r+=c[0]*v;g+=c[1]*v;b+=c[2]*v;sum+=v}});return sum?`rgb(${r/sum|0},${g/sum|0},${b/sum|0})`:'#30132e'}
function drawDrink(){const c=$('#drinkCanvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const total=Object.values(state.mix).reduce((a,b)=>a+b,0),h=Math.min(155,total*2);x.save();x.beginPath();x.moveTo(50,25);x.lineTo(70,205);x.quadraticCurveTo(110,228,150,205);x.lineTo(170,25);x.closePath();x.clip();let grad=x.createLinearGradient(0,220,0,40);grad.addColorStop(0,mixColor());grad.addColorStop(1,'rgba(255,255,255,.45)');x.fillStyle=grad;x.fillRect(48,210-h,125,h);if(state.ice!=='none'){x.fillStyle='rgba(210,235,255,.68)';for(let i=0;i<(state.ice==='crushed'?14:6);i++){let sz=state.ice==='crushed'?8:18;let px=65+(i*23)%85,py=188-(i%4)*18;x.save();x.translate(px,py);x.rotate(i*.4);x.fillRect(-sz/2,-sz/2,sz,sz);x.restore()}}x.restore();x.strokeStyle='rgba(220,235,255,.75)';x.lineWidth=4;x.beginPath();x.moveTo(50,25);x.lineTo(70,205);x.quadraticCurveTo(110,228,150,205);x.lineTo(170,25);x.stroke();}
function drawRecipe(){const c=$('#recipeGlass'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='#1a1027';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#8aa3d9';x.lineWidth=3;x.strokeRect(66,35,110,105);x.fillStyle=state.recipe===0?'#b01849':state.recipe===1?'#e06d25':state.recipe===2?'#8ed7c4':'#5d291e';x.fillRect(69,70,104,67);x.fillStyle='rgba(220,240,255,.65)';for(let i=0;i<5;i++)x.fillRect(78+i*18,82+(i%2)*16,13,13)}
function pour(){const ing=ingredients[state.selected];state.mix[ing.name]=Math.max(0,(state.mix[ing.name]||0)+state.step);state.shaken=false;render();tone(420,.04)}
function tone(freq,dur){try{const ac=new AudioContext(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;g.gain.value=.035;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+dur);o.stop(ac.currentTime+dur)}catch{}}
function score(){const r=recipes[state.recipe];let diff=0,max=0;const keys=new Set([...Object.keys(r.parts),...Object.keys(state.mix)]);keys.forEach(k=>{diff+=Math.abs((r.parts[k]||0)-(state.mix[k]||0));max+=(r.parts[k]||0)});let s=Math.max(0,100-diff*1.7);if(state.ice!==r.ice)s-=18;if(!state.shaken)s-=8;return Math.max(0,Math.round(s))}
function serve(){const s=score();let pay=Math.round(18+s*.55+guests[state.guest].heart*.1+state.upgrades.tip*5);state.cash+=pay;state.earned+=pay;state.rep=Math.min(100,state.rep+Math.round(s/20));guests[state.guest].heart=Math.min(100,guests[state.guest].heart+Math.round(s/25));toast(`${s}% Qualität · +€ ${pay}`);state.mix={};state.shaken=false;state.guest=(state.guest+1)%guests.length;state.recipe=(state.recipe+1)%recipes.length;if(state.earned>=state.goal){state.night++;state.earned=0;state.goal+=150;toast('Schichtziel erreicht – nächste Nacht!')}render()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
$$('[data-step]').forEach(b=>b.onclick=()=>{state.step=Number(b.dataset.step);if(state.step<0){const ing=ingredients[state.selected];state.mix[ing.name]=Math.max(0,(state.mix[ing.name]||0)+state.step);state.step=Math.abs(state.step);render()}else pour()});$('#pourBtn').onclick=pour;$$('[data-ice]').forEach(b=>b.onclick=()=>{state.ice=b.dataset.ice;render()});$('#shakeBtn').onclick=()=>{state.shaken=true;$('#shaker').classList.add('shaking');tone(140,.35);setTimeout(()=>$('#shaker').classList.remove('shaking'),700);toast('Drink geschüttelt')};$('#serveBtn').onclick=serve;$('#nextRecipe').onclick=()=>{state.recipe=(state.recipe+1)%recipes.length;render()};
function modal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}$('#closeModal').onclick=()=>$('#modal').close();$('#shopBtn').onclick=()=>modal(`<h2>Schwarzmarkt-Shop</h2><div class="shop-grid"><div class="shop-item"><h3>Präzisionsausgießer</h3><p>Bewertungsbonus bei kleinen Abweichungen.</p><button onclick="buy('precision',180)">€ 180 kaufen</button></div><div class="shop-item"><h3>VIP-Service</h3><p>Mehr Trinkgeld pro Drink.</p><button onclick="buy('tip',220)">€ 220 kaufen</button></div></div>`);window.buy=(k,p)=>{if(state.cash<p)return toast('Nicht genug Geld');state.cash-=p;state.upgrades[k]++;render();toast('Upgrade installiert')};$('#contactsBtn').onclick=()=>modal('<h2>Kontakte</h2>'+guests.map(g=>`<p><b>${g.name}</b> · ${g.role} · ♥ ${g.heart}/100</p>`).join(''));$('#missionsBtn').onclick=()=>modal(`<h2>Missionen</h2><p>Verdiene in dieser Nacht € ${state.goal}.</p><p>Serviere drei Drinks über 85% Qualität.</p><p>Erreiche 60 Beziehungspunkte mit einem Gast.</p>`);
render();
